# Generated by Django 3.2 on 2021-05-18 03:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todomodel',
            old_name='taskname',
            new_name='title',
        ),
        migrations.AddField(
            model_name='todomodel',
            name='desc',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='todomodel',
            name='startdate',
            field=models.DateField(),
        ),
    ]
